# Generated by Django 4.2 on 2025-11-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipoinfo',
            name='valor_compra',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
